// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_metrics is a generated GoMock package.
package mock_metrics

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDBMetrics is a mock of DBMetrics interface.
type MockDBMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockDBMetricsMockRecorder
}

// MockDBMetricsMockRecorder is the mock recorder for MockDBMetrics.
type MockDBMetricsMockRecorder struct {
	mock *MockDBMetrics
}

// NewMockDBMetrics creates a new mock instance.
func NewMockDBMetrics(ctrl *gomock.Controller) *MockDBMetrics {
	mock := &MockDBMetrics{ctrl: ctrl}
	mock.recorder = &MockDBMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBMetrics) EXPECT() *MockDBMetricsMockRecorder {
	return m.recorder
}

// IncreaseErrors mocks base method.
func (m *MockDBMetrics) IncreaseErrors(queryName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncreaseErrors", queryName)
}

// IncreaseErrors indicates an expected call of IncreaseErrors.
func (mr *MockDBMetricsMockRecorder) IncreaseErrors(queryName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseErrors", reflect.TypeOf((*MockDBMetrics)(nil).IncreaseErrors), queryName)
}

// ObserveResponseTime mocks base method.
func (m *MockDBMetrics) ObserveResponseTime(queryName string, observeTime float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveResponseTime", queryName, observeTime)
}

// ObserveResponseTime indicates an expected call of ObserveResponseTime.
func (mr *MockDBMetricsMockRecorder) ObserveResponseTime(queryName, observeTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveResponseTime", reflect.TypeOf((*MockDBMetrics)(nil).ObserveResponseTime), queryName, observeTime)
}
