linters-settings:
  gosec:
      checks:
        - all
        - '-G101' # disable the rule 
  gocognit:
    min-complexity: 60

linters:
  disable-all: true
  enable:
    - govet
    - gosimple
    - bodyclose
    - noctx
    - errcheck
    - gocognit
    - goconst
    - gofmt
    - gosec
  
  
   