linters-settings:
  gocognit:
    min-complexity: 60

linters:
  disable: 
    - typecheck
  enable:
    - govet
    - gosimple
    - bodyclose
    - noctx
    - errcheck
    - gocognit
    - goconst
    - gofmt
    - gosec
  
   