version: "3.3"

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    restart: always
    ports:
      - "8080:8080"
    networks:
      - YouNote-network
    volumes:
      - type: bind
        source: /var/log
        target: /var/log
      - type: bind
        source: /opt/images
        target: /opt/images
  postgres:
    env_file:
      - .env
    container_name: postgres
    image: postgres:15.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - YouNote-network
    volumes:
      - ./build/sql/create_tables.sql:/docker-entrypoint-initdb.d/initdb.sql
      - younote-db-data:/var/lib/postgresql/data
  proxy:
    container_name: nginx
    image: nginx
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/you-note.ru/fullchain.pem
        target: /etc/letsencrypt/live/you-note.ru/fullchain.pem
      - type: bind
        source: /etc/letsencrypt/live/you-note.ru/privkey.pem
        target: /etc/letsencrypt/live/you-note.ru/privkey.pem
      - type: bind
        source: /opt/images
        target: /opt/images
      - type: bind
        source: /opt/public
        target: /opt/public
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 443:443
      - 80:80
    networks:
      - YouNote-network

networks:
  YouNote-network:
    name: YouNote-network
    driver: bridge

volumes:
  younote-db-data: